卒業制作のREADME
ryota10000/portfolio pull request #1
Opened 2024-08-22 06:57 UTC by ryota10000

卒業制作のREADMEのレビューをよろしくお願いします。

2024-08-22 10:08 UTC, busitora requested changes
コメントしました！

2024-08-22 10:08 UTC, busitora commented on README.md
> +・クリックするだけで点数が分かるようにします。-> 4人用のサイトです。 https://yanohirota.com/mahjong-scoring-calculator/
`クリックするだけで点数が分かるようにします`

as is (現状)/ to be (理想)

を記載頂き、「どう」わかるようになるのか言語化できればしていただけますか! 👍

2024-08-22 10:08 UTC, busitora commented on README.md
> +親戚の集まりで３人麻雀をすることがあります。その時に不便だと感じたことを解消しようと考えたからです。
不便だと感じたことを解消しようと考えた

具体的には

- aaa
- bbb
- ccc

のように羅列するともっとよくなりますね！

2024-08-22 10:08 UTC, busitora commented on README.md
> +■ ユーザー層について
こちらも箇条書きにしましょう！

2024-08-22 10:08 UTC, busitora commented on README.md
> +点数計算がすぐできたり、確認できたりする。
```suggestion
点数計算がすぐできる
確認できる。
```

2024-08-22 10:08 UTC, busitora commented on README.md
> +現在の持ち点が分かるようにする。
```suggestion
現在の持ち点が分かる。
```

2024-08-22 10:08 UTC, busitora commented on README.md
> +Runteqで勉強を一緒にしているメンバーに試してもらう。
nitsですが、RUNTEQです！

2024-08-23 06:45 UTC, ryota10000 reviewed
レビューありがとうございました。
書かれていたことを参考に以下を変更しました。
・このサービスへの思い・作りたい理由
・サービスの利用イメージ
・ユーザーの獲得について

2024-08-23 08:16 UTC, TakenakaEri commented
ありがとうございます！
何点かご質問させてください。

ご相談に来ていただいた際に、最初は1人でも1人でも使用できるように計算機能を実装しようかなと思っているというお話をお伺いしたような記憶があるのですが、お間違いないでしょうか？
その場合、3人用でなくても2人用1人用という打ち出し方もできるかと思いますが、あえて3人用にしている理由をお伺いしたいです。

最初は1人の点数をつけれる機能を実装しておいて、MVP後に人数を設定できるようにして何人でも対応できるようにする...というような方法もあると思います。

実際の卓を囲んでの麻雀だと、2人だとできないのかどうか？や1人だとゲームの麻雀を使用するため、そもそも計算が必要ないなど、さまざまな理由でこの人数設定かと思うので、その辺りをお伺いしたいです。

また、このアプリに関しては、オンラインゲームではなく実際にあって卓を囲んで麻雀をするというのがポイントになるかと思うので、そのあたりを深掘りして機能を決定していっても良いかと感じました。
（ただし、こちらの意見に関しては、そういう内容を入れてほしいということではなく、考えをお伺いしたいという意図で書いております〜）

2024-08-23 08:37 UTC, ryota10000 commented
ご質問ありがとうございます。

３人用のサイトにした理由は以下の通りです。
・親戚での集まりで実際の卓でする３人麻雀をしかしておらず、その時に感じた課題を解決したいと感じたからです。
　親戚の集まりでゲームではなく現実の卓を囲んでやっています。
　実際の卓でするほうが楽しく感じる点が多いためです。稗を触る感覚や、緊張感が違う感じがします。

　
・作りたいのと似ているサイトを見つけたが、それが４人用だったので３人用を作りたいと感じたからです。

麻雀を一人で行うと基本的にゲームでするので、点数計算を機械が計算してくれるので必要性が少ないと感じます。
また、ゲーム麻雀であると試合結果に関してもゲーム上で確認できるため必要性が少なく感じています。

以上の点が、３人にこだわっている理由です。

2024-08-23 09:17 UTC, TakenakaEri commented
ありがとうございます！LTGMです！

3人用で思い入れがあればそれで大丈夫です！（計算方法なども3人用で必要ということで理解しました！）

2024-08-24 06:25 UTC, merged